Debug = true                #是否启用调试
Level = 0                   #日志级别,见zapcore.Level, debug:-1
Encoding = "console"        #编码格式，目前支持json/console，默认console
WriteToConsole = true       #输出到控制台
WriteToLogFile = true       #输出到日志文件
DisableColor = true         #禁止显示日志颜色
DisableCaller = true        #禁止显示调用路径
EnableShortCaller = false   #显示短调用路径
EnableStackTrace = false    #显示堆栈
CallerSkip = 0              #调用堆栈跳过行数
LogFilePath = ""            #日志文件名称，默认为 ./log/app.log
LogFileMaxSize = 0          #日志文件切割最大大小(单位M),默认100M
LogFileMaxAge = 7           #日志文件保存最大天数，超过此天数的旧日志文件将被删除，默认无限制
LogFileMaxBackups = 10      #日志文件最大备份数，超过此数的就日志文件将被删除，默认无限制
CompressLogFile = false     #是否压缩日志文件